import type { Product, Category } from './types';
import { LayersIcon, SparklesIcon, TagIcon, SmartphoneIcon, DesktopIcon, HomeIcon, BackpackIcon, BookIcon, MixIcon } from './components/icons/CategoryIcons';

export const categories: Category[] = [
  { id: 'all', name: 'All', count: 0, icon: LayersIcon },
  { id: 'new', name: 'New', count: 0, icon: SparklesIcon },
  { id: 'picks', name: 'Picks', count: 0, icon: TagIcon },
  { id: 'tech', name: 'Tech', count: 116, icon: SmartphoneIcon },
  { id: 'workspace', name: 'Workspace', count: 135, icon: DesktopIcon },
  { id: 'home', name: 'Home', count: 60, icon: HomeIcon },
  { id: 'carry', name: 'Carry', count: 85, icon: BackpackIcon },
  { id: 'books', name: 'Books', count: 31, icon: BookIcon },
  { id: 'lifestyle', name: 'Lifestyle', count: 21, icon: MixIcon },
];

export const products: Product[] = [
  {
    id: 1,
    brand: 'Apple',
    category: 'Tech',
    name: 'Studio Display',
    imageUrl: '/studio display.webp',
  },
  {
    id: 2,
    brand: 'Grams28',
    category: 'Carry',
    name: '151 Stealth Backpack',
    imageUrl: '/Grams28_151 Stealth Backpack.webp',
  },
  {
    id: 3,
    brand: 'Herman Miller',
    category: 'Workspace',
    name: 'Aeron',
    imageUrl: '/aeron.webp',
  },
  {
    id: 4,
    brand: 'Apple',
    category: 'Tech',
    name: 'iPhone 14 Pro',
    imageUrl: '/workLouder.webp',
    isStaffPick: true,
  },
  {
    id: 5,
    brand: 'Porsche',
    category: 'Lifestyle',
    name: '911 Turbo S',
    imageUrl: '/911.webp',
    isStaffPick: true,
  },
  {
    id: 6,
    brand: 'Omega',
    category: 'Lifestyle',
    name: 'Speedmaster',
    imageUrl: '/Omega_Speedmaster.webp',
    isStaffPick: true,
  },
  {
    id: 7,
    brand: 'Apple',
    category: 'Tech',
    name: 'iPhone Air',
    imageUrl: '/Apple_iPhone Air.webp',
  },
  {
    id: 8,
    brand: 'Apple',
    category: 'Tech',
    name: 'iPhone Pro 17',
    imageUrl: '/Apple_iPhone Pro 17.webp',
  },
  {
    id: 9,
    brand: 'Bang',
    category: 'Home',
    name: 'Lớp Small Square in Orange Acrylic CE',
    imageUrl: '/Bang_Lớp small square in orange acrylic CE.webp',
  },
  {
    id: 10,
    brand: 'Bionic',
    category: 'Home',
    name: 'Valet Tray',
    imageUrl: '/Bionic_Valet Tray.webp',
  },
  {
    id: 11,
    brand: 'Blanked',
    category: 'Workspace',
    name: 'Desktop Folder',
    imageUrl: '/Blanked_Desktop Folder.webp',
  },
  {
    id: 12,
    brand: 'Blanked',
    category: 'Workspace',
    name: 'Industrial Bookstand',
    imageUrl: '/Blanked_Industrial Bookstand.webp',
  },
  {
    id: 13,
    brand: 'Breda',
    category: 'Lifestyle',
    name: 'Pulse (Tandem)',
    imageUrl: '/Breda_Pulse (Tandem).webp',
  },
  {
    id: 14,
    brand: 'Crust',
    category: 'Home',
    name: 'P–1 Pepper Mill',
    imageUrl: '/Crust_P–1 Pepper Mill.webp',
  },
  {
    id: 15,
    brand: 'Dyson',
    category: 'Home',
    name: 'Solarcycle Morph Floor',
    imageUrl: '/Dyson_Solarcycle Morph Floor.webp',
  },
  {
    id: 16,
    brand: 'Fellow',
    category: 'Home',
    name: 'Stagg',
    imageUrl: '/fellow_stagg.webp',
  },
  {
    id: 17,
    brand: 'Ferrari',
    category: 'Lifestyle',
    name: 'Roma',
    imageUrl: '/Ferrari_Roma.webp',
    isStaffPick: true,
  },
  {
    id: 18,
    brand: 'Grau',
    category: 'Home',
    name: 'Salt',
    imageUrl: '/Grau_Salt.webp',
  },
  {
    id: 19,
    brand: 'HS82',
    category: 'Home',
    name: 'ClockClock 24',
    imageUrl: '/HS82_ClockClock 24.webp',
  },
  {
    id: 20,
    brand: 'Kismas',
    category: 'Home',
    name: 'Doric Lamp 01',
    imageUrl: '/Kismas_Doric Lamp 01.webp',
  },
  {
    id: 21,
    brand: 'Lego',
    category: 'Lifestyle',
    name: 'Icons 10295 Porsche 911',
    imageUrl: '/Lego _ Icons 10295 Porsche 911.webp',
  },
  {
    id: 22,
    brand: 'Leica',
    category: 'Tech',
    name: 'Q3',
    imageUrl: '/Leica Q3.webp',
    isStaffPick: true,
  },
  {
    id: 23,
    brand: 'Ligne Roset',
    category: 'Home',
    name: 'Togo Loveseat',
    imageUrl: '/ligneroset_TogoLoveseat.webp',
  },
  {
    id: 24,
    brand: 'Lofree',
    category: 'Workspace',
    name: 'Flow 2',
    imageUrl: '/Lofree_ Flow 2.webp',
  },
  {
    id: 25,
    brand: 'Noguchi',
    category: 'Home',
    name: 'Table',
    imageUrl: '/noguchi_table.webp',
  },
  {
    id: 26,
    brand: 'Nomad',
    category: 'Tech',
    name: 'Base One Max 3-in-1',
    imageUrl: '/Nomad_ Base One Max 3-in-1.webp',
  },
  {
    id: 27,
    brand: 'Nothing',
    category: 'Tech',
    name: 'Headphones',
    imageUrl: '/Nothing_Headphones(1).webp',
  },
  {
    id: 28,
    brand: 'Nothing',
    category: 'Tech',
    name: 'Phone (3)',
    imageUrl: '/Nothing_Phone(3).webp',
  },
  {
    id: 29,
    brand: 'Phaidon',
    category: 'Books',
    name: 'Dieter Rams: The Complete Works',
    imageUrl: '/Phaidon_Dieter Rams_ The Complete Works.webp',
  },
  {
    id: 30,
    brand: 'Phaidon',
    category: 'Books',
    name: 'The Design Book',
    imageUrl: '/Phaidon_The Design Book.webp',
  },
  {
    id: 31,
    brand: 'Rimowa',
    category: 'Carry',
    name: 'Classic Cabin',
    imageUrl: '/Rimowa_Classic Cabin.webp',
    isStaffPick: true,
  },
  {
    id: 32,
    brand: 'Rolex',
    category: 'Lifestyle',
    name: 'Datejust',
    imageUrl: '/Rolex_Datejust.webp',
    isStaffPick: true,
  },
  {
    id: 33,
    brand: 'Serica',
    category: 'Lifestyle',
    name: 'Réf. 1174-1 Parade',
    imageUrl: '/Serica_Réf. 1174-1 Parade.webp',
  },
  {
    id: 34,
    brand: 'Sigma',
    category: 'Tech',
    name: 'BF',
    imageUrl: '/Sigma_BF.webp',
  },
  {
    id: 35,
    brand: 'Sony',
    category: 'Tech',
    name: 'WH-1000XM5',
    imageUrl: '/Sony_WH 1000XM5.webp',
  },
  {
    id: 36,
    brand: 'Subminimal',
    category: 'Home',
    name: 'Subscale',
    imageUrl: '/Subminimal_Subscale.webp',
  },
  {
    id: 37,
    brand: 'Taschen',
    category: 'Books',
    name: 'Virgil Abloh. Nike. ICONS',
    imageUrl: '/Taschen_Virgil Abloh. Nike. ICONS.webp',
  },
  {
    id: 38,
    brand: 'Xbloom',
    category: 'Home',
    name: 'Studio',
    imageUrl: '/xbloomstudio.webp',
  },
];
