import {
    BackpackIcon,
    BookIcon,
    DesktopIcon,
    HomeIcon,
    LayersIcon,
    MixIcon,
    SmartphoneIcon,
    SparklesIcon,
    TagIcon,
} from '@/components/icons/CategoryIcons';
import type { Category, Product } from '@/types';

export const categories: Category[] = [
    { id: 'all', name: 'All', count: 0, icon: LayersIcon },
    { id: 'new', name: 'New', count: 0, icon: SparklesIcon },
    { id: 'picks', name: 'Picks', count: 0, icon: TagIcon },
    { id: 'tech', name: 'Tech', count: 116, icon: SmartphoneIcon },
    { id: 'workspace', name: 'Workspace', count: 135, icon: DesktopIcon },
    { id: 'home', name: 'Home', count: 60, icon: HomeIcon },
    { id: 'carry', name: 'Carry', count: 85, icon: BackpackIcon },
    { id: 'books', name: 'Books', count: 31, icon: BookIcon },
    { id: 'lifestyle', name: 'Lifestyle', count: 21, icon: MixIcon },
];

export const products: Product[] = [
    {
        id: 1,
        brand: 'Apple',
        category: 'Tech',
        name: 'Studio Display',
        imageUrl: '/studio display.webp',
        price: 1599,
    },
    {
        id: 2,
        brand: 'Grams28',
        category: 'Carry',
        name: '151 Stealth Backpack',
        imageUrl: '/Grams28_151 Stealth Backpack.webp',
        price: 299,
    },
    {
        id: 3,
        brand: 'Herman Miller',
        category: 'Workspace',
        name: 'Aeron',
        imageUrl: '/aeron.webp',
        price: 1395,
    },
    {
        id: 4,
        brand: 'WorkLouder',
        category: 'Tech',
        name: 'Mechanical Keyboard',
        imageUrl: '/workLouder.webp',
        price: 299,
        isStaffPick: true,
    },
    {
        id: 5,
        brand: 'Porsche',
        category: 'Lifestyle',
        name: '911 Turbo S',
        imageUrl: '/911.webp',
        price: 207000,
        isStaffPick: true,
    },
    {
        id: 6,
        brand: 'Omega',
        category: 'Lifestyle',
        name: 'Speedmaster',
        imageUrl: '/Omega_Speedmaster.webp',
        price: 6400,
        isStaffPick: true,
    },
    {
        id: 7,
        brand: 'Apple',
        category: 'Tech',
        name: 'iPhone Air',
        imageUrl: '/Apple_iPhone Air.webp',
        price: 599,
    },
    {
        id: 8,
        brand: 'Apple',
        category: 'Tech',
        name: 'iPhone 17 Pro',
        imageUrl: '/Apple_iPhone Pro 17.webp',
        price: 1199,
    },
    {
        id: 9,
        brand: 'Bang',
        category: 'Home',
        name: 'Small Square in Orange Acrylic CE',
        imageUrl: '/Bang_Small_Square_Orange_Acrylic_CE.webp',
        price: 85,
    },
    {
        id: 10,
        brand: 'Bionic',
        category: 'Home',
        name: 'Valet Tray',
        imageUrl: '/Bionic_Valet Tray.webp',
        price: 125,
    },
    {
        id: 11,
        brand: 'Blanked',
        category: 'Workspace',
        name: 'Desktop Folder',
        imageUrl: '/Blanked_Desktop Folder.webp',
        price: 95,
    },
    {
        id: 12,
        brand: 'Blanked',
        category: 'Workspace',
        name: 'Industrial Bookstand',
        imageUrl: '/Blanked_Industrial Bookstand.webp',
        price: 145,
    },
    {
        id: 13,
        brand: 'Breda',
        category: 'Lifestyle',
        name: 'Pulse (Tandem)',
        imageUrl: '/Breda_Pulse (Tandem).webp',
        price: 129,
    },
    {
        id: 14,
        brand: 'Crust',
        category: 'Home',
        name: 'P–1 Pepper Mill',
        imageUrl: '/Crust_P–1 Pepper Mill.webp',
        price: 155,
    },
    {
        id: 15,
        brand: 'Dyson',
        category: 'Home',
        name: 'Solarcycle Morph',
        imageUrl: '/Dyson_Solarcycle Morph Floor.webp',
        price: 649,
    },
    {
        id: 16,
        brand: 'Fellow',
        category: 'Home',
        name: 'Stagg EKG',
        imageUrl: '/fellow_stagg.webp',
        price: 189,
    },
    {
        id: 17,
        brand: 'Ferrari',
        category: 'Lifestyle',
        name: 'Roma',
        imageUrl: '/Ferrari_Roma.webp',
        price: 247000,
        isStaffPick: true,
    },
    {
        id: 18,
        brand: 'Grau',
        category: 'Home',
        name: 'Salt',
        imageUrl: '/Grau_Salt.webp',
        price: 75,
    },
    {
        id: 19,
        brand: 'HS82',
        category: 'Home',
        name: 'ClockClock 24',
        imageUrl: '/HS82_ClockClock 24.webp',
        price: 4495,
    },
    {
        id: 20,
        brand: 'Kismas',
        category: 'Home',
        name: 'Doric Lamp 01',
        imageUrl: '/Kismas_Doric Lamp 01.webp',
        price: 495,
    },
    {
        id: 21,
        brand: 'Lego',
        category: 'Lifestyle',
        name: 'Icons 10295 Porsche 911',
        imageUrl: '/Lego _ Icons 10295 Porsche 911.webp',
        price: 169,
    },
    {
        id: 22,
        brand: 'Leica',
        category: 'Tech',
        name: 'Q3',
        imageUrl: '/Leica Q3.webp',
        price: 5995,
        isStaffPick: true,
    },
    {
        id: 23,
        brand: 'Ligne Roset',
        category: 'Home',
        name: 'Togo Loveseat',
        imageUrl: '/ligneroset_TogoLoveseat.webp',
        price: 5495,
    },
    {
        id: 24,
        brand: 'Lofree',
        category: 'Workspace',
        name: 'Flow 2',
        imageUrl: '/Lofree_ Flow 2.webp',
        price: 149,
    },
    {
        id: 25,
        brand: 'Herman Miller',
        category: 'Home',
        name: 'Noguchi Table',
        imageUrl: '/noguchi_table.webp',
        price: 3795,
    },
    {
        id: 26,
        brand: 'Nomad',
        category: 'Tech',
        name: 'Base One Max 3-in-1',
        imageUrl: '/Nomad_ Base One Max 3-in-1.webp',
        price: 249,
    },
    {
        id: 27,
        brand: 'Nothing',
        category: 'Tech',
        name: 'Ear (stick)',
        imageUrl: '/Nothing_Headphones(1).webp',
        price: 99,
    },
    {
        id: 28,
        brand: 'Nothing',
        category: 'Tech',
        name: 'Nothing Phone (3)',
        imageUrl: '/Nothing_Phone(3).webp',
        price: 699,
    },
    {
        id: 29,
        brand: 'Phaidon',
        category: 'Books',
        name: 'Dieter Rams: The Complete Works',
        imageUrl: '/Phaidon_Dieter Rams_ The Complete Works.webp',
        price: 75,
    },
    {
        id: 30,
        brand: 'Phaidon',
        category: 'Books',
        name: 'The Design Book',
        imageUrl: '/Phaidon_The Design Book.webp',
        price: 65,
    },
    {
        id: 31,
        brand: 'Rimowa',
        category: 'Carry',
        name: 'Classic Cabin',
        imageUrl: '/Rimowa_Classic Cabin.webp',
        price: 1650,
        isStaffPick: true,
    },
    {
        id: 32,
        brand: 'Rolex',
        category: 'Lifestyle',
        name: 'Datejust',
        imageUrl: '/Rolex_Datejust.webp',
        price: 8950,
        isStaffPick: true,
    },
    {
        id: 33,
        brand: 'Serica',
        category: 'Lifestyle',
        name: 'Réf. 1174-1 Parade',
        imageUrl: '/Serica_Réf1174-1 Parade.webp',
        price: 899,
    },
    {
        id: 34,
        brand: 'Sigma',
        category: 'Tech',
        name: 'BF',
        imageUrl: '/Sigma_BF.webp',
        price: 199,
    },
    {
        id: 35,
        brand: 'Sony',
        category: 'Tech',
        name: 'WH-1000XM5',
        imageUrl: '/Sony_WH 1000XM5.webp',
        price: 399,
    },
    {
        id: 36,
        brand: 'Subminimal',
        category: 'Home',
        name: 'Subscale',
        imageUrl: '/Subminimal_Subscale.webp',
        price: 175,
    },
    {
        id: 37,
        brand: 'Taschen',
        category: 'Books',
        name: 'Virgil Abloh. Nike. ICONS',
        imageUrl: '/Taschen_Virgil Abloh. Nike. ICONS.webp',
        price: 150,
    },
    {
        id: 38,
        brand: 'Xbloom',
        category: 'Home',
        name: 'Studio',
        imageUrl: '/xbloomstudio.webp',
        price: 1299,
    },
    {
        id: 39,
        brand: 'Apple',
        category: 'Tech',
        name: 'Pro Display XDR',
        imageUrl: '/apple-pro-display-xdr.png',
        price: 4999,
    },
];
